export { IoMenuSharp as MenuIcon } from 'react-icons/io5';
export { MdTimer as BeginDateIcon } from 'react-icons/md';
export { MdTimerOff as EndDateIcon } from 'react-icons/md';
export { MdDateRange as DateRangeIcon } from 'react-icons/md';
export { MdTimer as TimeIcon } from 'react-icons/md';
export { RiCalendarCheckLine as RegistrationDateIcon } from 'react-icons/ri';
export { AiOutlineAndroid as AndroidIcon } from 'react-icons/ai';
export { SiIos as IosIcon } from 'react-icons/si';
export { MdMoreVert as AdditionalMenuIcon } from 'react-icons/md';
export { MdTimeline as TimelineIcon  } from 'react-icons/md';
export { RiCalendarLine as CurrentDateIcon } from 'react-icons/ri';
export { RiCalendarEventLine as WorkDateIcon } from 'react-icons/ri';
export { RiCalendarTodoLine as ScheduleIcon } from 'react-icons/ri';
export { FiRefreshCcw as RefreshIcon } from 'react-icons/fi';
export { RiAdminLine as AdminIcon } from 'react-icons/ri';
export { RiUserLocationLine as UserIcon } from 'react-icons/ri';
export { IoGridOutline as ListsIcon } from 'react-icons/io5';
export { IoSettingsOutline as SettingsIcon } from 'react-icons/io5';
export { IoHomeOutline as HomeIcon } from 'react-icons/io5';
export { IoInformationCircleOutline as AboutIcon } from 'react-icons/io5';
export { IoExitOutline as ExitIcon } from 'react-icons/io5';
export { CgRemoveR as DeleteIcon } from 'react-icons/cg';
export { CgAddR as AddIcon } from 'react-icons/cg';
export { BiEdit as EditIcon } from 'react-icons/bi';
export { IoWarningSharp as WarningIcon } from 'react-icons/io5';
export { IoInformationCircleSharp as InformationIcon } from 'react-icons/io5';
export { BsBoxArrowInLeft as  WorkDateBackwardIcon } from 'react-icons/bs';
export { BsBoxArrowInRight as WorkDateForwardIcon } from 'react-icons/bs';
export { IoTodayOutline as WorkDateTodayIcon } from 'react-icons/io5';
export { IoCloseOutline as CloseIcon } from 'react-icons/io5';
export { RiFileExcel2Line as ExportToXlsxIcon } from 'react-icons/ri';
export { MdMailOutline as EmailIcon } from 'react-icons/md';
export { RiBatteryLine as LowPowerModeEnabledIcon } from 'react-icons/ri';
export { RiBatteryChargeLine as LowPowerModeDisabledIcon } from 'react-icons/ri';
export { RiBatteryLowLine as BatteryLevelIcon } from 'react-icons/ri';
export { IoMdBatteryCharging as ChargingLevelIcon } from 'react-icons/io';
export { IoBatteryChargingOutline as BatteryIcon } from 'react-icons/io5';
export { MdErrorOutline as ErrorIcon } from 'react-icons/md';
export { VscDebug as DebugIcon } from 'react-icons/vsc';
export { IoEllipsisHorizontal as ExtensionIcon } from 'react-icons/io5';
export { IoCloudDownloadOutline as DownloadIcon } from 'react-icons/io5';
export { ImFileZip as PackageIcon } from 'react-icons/im';
export { IoHardwareChipOutline as  GpioIcon } from 'react-icons/io5';
export { VscTools as ServiceIcon } from 'react-icons/vsc';


import { MdMoreVert } from 'react-icons/md';
export const GridAdditionalMenuIcon = () => <MdMoreVert style={ { cursor: 'pointer' } } size={ 18 } />
