from enum import IntEnum

class TemperatureSensorChannels(IntEnum):
    OUTDOOR_TEMPERATURE = 0
    ROOM_TEMPERATURE = 1
    SUPPLY_PIPE_TEMPERATURE_1 = 2
    RETURN_PIPE_TEMPERATURE_1 = 3
    SUPPLY_PIPE_TEMPERATURE_2 = 4
    RETURN_PIPE_TEMPERATURE_2 = 5
